'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DataSet6
    Inherits DataSet
    
    Private tableCosts As CostsDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("Costs")) Is Nothing) Then
                Me.Tables.Add(New CostsDataTable(ds.Tables("Costs")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property Costs As CostsDataTable
        Get
            Return Me.tableCosts
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DataSet6 = CType(MyBase.Clone,DataSet6)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("Costs")) Is Nothing) Then
            Me.Tables.Add(New CostsDataTable(ds.Tables("Costs")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableCosts = CType(Me.Tables("Costs"),CostsDataTable)
        If (Not (Me.tableCosts) Is Nothing) Then
            Me.tableCosts.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DataSet6"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DataSet6.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableCosts = New CostsDataTable
        Me.Tables.Add(Me.tableCosts)
    End Sub
    
    Private Function ShouldSerializeCosts() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub CostsRowChangeEventHandler(ByVal sender As Object, ByVal e As CostsRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class CostsDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnAmount As DataColumn
        
        Private columnCost As DataColumn
        
        Private columnCostDate As DataColumn
        
        Private columnID As DataColumn
        
        Friend Sub New()
            MyBase.New("Costs")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property AmountColumn As DataColumn
            Get
                Return Me.columnAmount
            End Get
        End Property
        
        Friend ReadOnly Property CostColumn As DataColumn
            Get
                Return Me.columnCost
            End Get
        End Property
        
        Friend ReadOnly Property CostDateColumn As DataColumn
            Get
                Return Me.columnCostDate
            End Get
        End Property
        
        Friend ReadOnly Property IDColumn As DataColumn
            Get
                Return Me.columnID
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As CostsRow
            Get
                Return CType(Me.Rows(index),CostsRow)
            End Get
        End Property
        
        Public Event CostsRowChanged As CostsRowChangeEventHandler
        
        Public Event CostsRowChanging As CostsRowChangeEventHandler
        
        Public Event CostsRowDeleted As CostsRowChangeEventHandler
        
        Public Event CostsRowDeleting As CostsRowChangeEventHandler
        
        Public Overloads Sub AddCostsRow(ByVal row As CostsRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddCostsRow(ByVal Amount As Integer, ByVal Cost As String, ByVal CostDate As Date) As CostsRow
            Dim rowCostsRow As CostsRow = CType(Me.NewRow,CostsRow)
            rowCostsRow.ItemArray = New Object() {Amount, Cost, CostDate, Nothing}
            Me.Rows.Add(rowCostsRow)
            Return rowCostsRow
        End Function
        
        Public Function FindByID(ByVal ID As Integer) As CostsRow
            Return CType(Me.Rows.Find(New Object() {ID}),CostsRow)
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As CostsDataTable = CType(MyBase.Clone,CostsDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New CostsDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnAmount = Me.Columns("Amount")
            Me.columnCost = Me.Columns("Cost")
            Me.columnCostDate = Me.Columns("CostDate")
            Me.columnID = Me.Columns("ID")
        End Sub
        
        Private Sub InitClass()
            Me.columnAmount = New DataColumn("Amount", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnAmount)
            Me.columnCost = New DataColumn("Cost", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCost)
            Me.columnCostDate = New DataColumn("CostDate", GetType(System.DateTime), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnCostDate)
            Me.columnID = New DataColumn("ID", GetType(System.Int32), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnID)
            Me.Constraints.Add(New UniqueConstraint("Constraint1", New DataColumn() {Me.columnID}, true))
            Me.columnID.AutoIncrement = true
            Me.columnID.AllowDBNull = false
            Me.columnID.Unique = true
        End Sub
        
        Public Function NewCostsRow() As CostsRow
            Return CType(Me.NewRow,CostsRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New CostsRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(CostsRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.CostsRowChangedEvent) Is Nothing) Then
                RaiseEvent CostsRowChanged(Me, New CostsRowChangeEvent(CType(e.Row,CostsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.CostsRowChangingEvent) Is Nothing) Then
                RaiseEvent CostsRowChanging(Me, New CostsRowChangeEvent(CType(e.Row,CostsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.CostsRowDeletedEvent) Is Nothing) Then
                RaiseEvent CostsRowDeleted(Me, New CostsRowChangeEvent(CType(e.Row,CostsRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.CostsRowDeletingEvent) Is Nothing) Then
                RaiseEvent CostsRowDeleting(Me, New CostsRowChangeEvent(CType(e.Row,CostsRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveCostsRow(ByVal row As CostsRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class CostsRow
        Inherits DataRow
        
        Private tableCosts As CostsDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableCosts = CType(Me.Table,CostsDataTable)
        End Sub
        
        Public Property Amount As Integer
            Get
                Try 
                    Return CType(Me(Me.tableCosts.AmountColumn),Integer)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableCosts.AmountColumn) = value
            End Set
        End Property
        
        Public Property Cost As String
            Get
                Try 
                    Return CType(Me(Me.tableCosts.CostColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableCosts.CostColumn) = value
            End Set
        End Property
        
        Public Property CostDate As Date
            Get
                Try 
                    Return CType(Me(Me.tableCosts.CostDateColumn),Date)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableCosts.CostDateColumn) = value
            End Set
        End Property
        
        Public Property ID As Integer
            Get
                Return CType(Me(Me.tableCosts.IDColumn),Integer)
            End Get
            Set
                Me(Me.tableCosts.IDColumn) = value
            End Set
        End Property
        
        Public Function IsAmountNull() As Boolean
            Return Me.IsNull(Me.tableCosts.AmountColumn)
        End Function
        
        Public Sub SetAmountNull()
            Me(Me.tableCosts.AmountColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCostNull() As Boolean
            Return Me.IsNull(Me.tableCosts.CostColumn)
        End Function
        
        Public Sub SetCostNull()
            Me(Me.tableCosts.CostColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsCostDateNull() As Boolean
            Return Me.IsNull(Me.tableCosts.CostDateColumn)
        End Function
        
        Public Sub SetCostDateNull()
            Me(Me.tableCosts.CostDateColumn) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class CostsRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As CostsRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As CostsRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As CostsRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
