'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Data
Imports System.Runtime.Serialization
Imports System.Xml


<Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Diagnostics.DebuggerStepThrough(),  _
 System.ComponentModel.ToolboxItem(true)>  _
Public Class DataSet7
    Inherits DataSet
    
    Private tableHistory As HistoryDataTable
    
    Public Sub New()
        MyBase.New
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    Protected Sub New(ByVal info As SerializationInfo, ByVal context As StreamingContext)
        MyBase.New
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(System.String)),String)
        If (Not (strSchema) Is Nothing) Then
            Dim ds As DataSet = New DataSet
            ds.ReadXmlSchema(New XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("History")) Is Nothing) Then
                Me.Tables.Add(New HistoryDataTable(ds.Tables("History")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.InitClass
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler Me.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property History As HistoryDataTable
        Get
            Return Me.tableHistory
        End Get
    End Property
    
    Public Overrides Function Clone() As DataSet
        Dim cln As DataSet7 = CType(MyBase.Clone,DataSet7)
        cln.InitVars
        Return cln
    End Function
    
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As XmlReader)
        Me.Reset
        Dim ds As DataSet = New DataSet
        ds.ReadXml(reader)
        If (Not (ds.Tables("History")) Is Nothing) Then
            Me.Tables.Add(New HistoryDataTable(ds.Tables("History")))
        End If
        Me.DataSetName = ds.DataSetName
        Me.Prefix = ds.Prefix
        Me.Namespace = ds.Namespace
        Me.Locale = ds.Locale
        Me.CaseSensitive = ds.CaseSensitive
        Me.EnforceConstraints = ds.EnforceConstraints
        Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
        Me.InitVars
    End Sub
    
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New XmlTextReader(stream), Nothing)
    End Function
    
    Friend Sub InitVars()
        Me.tableHistory = CType(Me.Tables("History"),HistoryDataTable)
        If (Not (Me.tableHistory) Is Nothing) Then
            Me.tableHistory.InitVars
        End If
    End Sub
    
    Private Sub InitClass()
        Me.DataSetName = "DataSet7"
        Me.Prefix = ""
        Me.Namespace = "http://www.tempuri.org/DataSet7.xsd"
        Me.Locale = New System.Globalization.CultureInfo("en-US")
        Me.CaseSensitive = false
        Me.EnforceConstraints = true
        Me.tableHistory = New HistoryDataTable
        Me.Tables.Add(Me.tableHistory)
    End Sub
    
    Private Function ShouldSerializeHistory() As Boolean
        Return false
    End Function
    
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    Public Delegate Sub HistoryRowChangeEventHandler(ByVal sender As Object, ByVal e As HistoryRowChangeEvent)
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class HistoryDataTable
        Inherits DataTable
        Implements System.Collections.IEnumerable
        
        Private columnOrder As DataColumn
        
        Private columnExpr1 As DataColumn
        
        Friend Sub New()
            MyBase.New("History")
            Me.InitClass
        End Sub
        
        Friend Sub New(ByVal table As DataTable)
            MyBase.New(table.TableName)
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
            Me.DisplayExpression = table.DisplayExpression
        End Sub
        
        <System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        Friend ReadOnly Property OrderColumn As DataColumn
            Get
                Return Me.columnOrder
            End Get
        End Property
        
        Friend ReadOnly Property Expr1Column As DataColumn
            Get
                Return Me.columnExpr1
            End Get
        End Property
        
        Public Default ReadOnly Property Item(ByVal index As Integer) As HistoryRow
            Get
                Return CType(Me.Rows(index),HistoryRow)
            End Get
        End Property
        
        Public Event HistoryRowChanged As HistoryRowChangeEventHandler
        
        Public Event HistoryRowChanging As HistoryRowChangeEventHandler
        
        Public Event HistoryRowDeleted As HistoryRowChangeEventHandler
        
        Public Event HistoryRowDeleting As HistoryRowChangeEventHandler
        
        Public Overloads Sub AddHistoryRow(ByVal row As HistoryRow)
            Me.Rows.Add(row)
        End Sub
        
        Public Overloads Function AddHistoryRow(ByVal Order As String, ByVal Expr1 As Double) As HistoryRow
            Dim rowHistoryRow As HistoryRow = CType(Me.NewRow,HistoryRow)
            rowHistoryRow.ItemArray = New Object() {Order, Expr1}
            Me.Rows.Add(rowHistoryRow)
            Return rowHistoryRow
        End Function
        
        Public Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        Public Overrides Function Clone() As DataTable
            Dim cln As HistoryDataTable = CType(MyBase.Clone,HistoryDataTable)
            cln.InitVars
            Return cln
        End Function
        
        Protected Overrides Function CreateInstance() As DataTable
            Return New HistoryDataTable
        End Function
        
        Friend Sub InitVars()
            Me.columnOrder = Me.Columns("Order")
            Me.columnExpr1 = Me.Columns("Expr1")
        End Sub
        
        Private Sub InitClass()
            Me.columnOrder = New DataColumn("Order", GetType(System.String), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnOrder)
            Me.columnExpr1 = New DataColumn("Expr1", GetType(System.Double), Nothing, System.Data.MappingType.Element)
            Me.Columns.Add(Me.columnExpr1)
        End Sub
        
        Public Function NewHistoryRow() As HistoryRow
            Return CType(Me.NewRow,HistoryRow)
        End Function
        
        Protected Overrides Function NewRowFromBuilder(ByVal builder As DataRowBuilder) As DataRow
            Return New HistoryRow(builder)
        End Function
        
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(HistoryRow)
        End Function
        
        Protected Overrides Sub OnRowChanged(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.HistoryRowChangedEvent) Is Nothing) Then
                RaiseEvent HistoryRowChanged(Me, New HistoryRowChangeEvent(CType(e.Row,HistoryRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowChanging(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.HistoryRowChangingEvent) Is Nothing) Then
                RaiseEvent HistoryRowChanging(Me, New HistoryRowChangeEvent(CType(e.Row,HistoryRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleted(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.HistoryRowDeletedEvent) Is Nothing) Then
                RaiseEvent HistoryRowDeleted(Me, New HistoryRowChangeEvent(CType(e.Row,HistoryRow), e.Action))
            End If
        End Sub
        
        Protected Overrides Sub OnRowDeleting(ByVal e As DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.HistoryRowDeletingEvent) Is Nothing) Then
                RaiseEvent HistoryRowDeleting(Me, New HistoryRowChangeEvent(CType(e.Row,HistoryRow), e.Action))
            End If
        End Sub
        
        Public Sub RemoveHistoryRow(ByVal row As HistoryRow)
            Me.Rows.Remove(row)
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class HistoryRow
        Inherits DataRow
        
        Private tableHistory As HistoryDataTable
        
        Friend Sub New(ByVal rb As DataRowBuilder)
            MyBase.New(rb)
            Me.tableHistory = CType(Me.Table,HistoryDataTable)
        End Sub
        
        Public Property Order As String
            Get
                Try 
                    Return CType(Me(Me.tableHistory.OrderColumn),String)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableHistory.OrderColumn) = value
            End Set
        End Property
        
        Public Property Expr1 As Double
            Get
                Try 
                    Return CType(Me(Me.tableHistory.Expr1Column),Double)
                Catch e As InvalidCastException
                    Throw New StrongTypingException("Cannot get value because it is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableHistory.Expr1Column) = value
            End Set
        End Property
        
        Public Function IsOrderNull() As Boolean
            Return Me.IsNull(Me.tableHistory.OrderColumn)
        End Function
        
        Public Sub SetOrderNull()
            Me(Me.tableHistory.OrderColumn) = System.Convert.DBNull
        End Sub
        
        Public Function IsExpr1Null() As Boolean
            Return Me.IsNull(Me.tableHistory.Expr1Column)
        End Function
        
        Public Sub SetExpr1Null()
            Me(Me.tableHistory.Expr1Column) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThrough()>  _
    Public Class HistoryRowChangeEvent
        Inherits EventArgs
        
        Private eventRow As HistoryRow
        
        Private eventAction As DataRowAction
        
        Public Sub New(ByVal row As HistoryRow, ByVal action As DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        Public ReadOnly Property Row As HistoryRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        Public ReadOnly Property Action As DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
